version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: secure_auth_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-volume:/data/db
volumes:
  mongo-data-volume:
